codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 80%
        threshold: 0%

flags:
  server-unit:
    paths:
      - apps/server/src/
    carryforward: true
  server-integration:
    paths:
      - apps/server/src/
    carryforward: true
  web:
    paths:
      - apps/web/src/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
